COPY INTO outputs
FROM @LITECOIN_STAGE
FILE_FORMAT = (FORMAT_NAME = LITECOIN_TSV_FORMAT)
PATTERN = '.*outputs.*'
ON_ERROR = 'skip_file';

COPY INTO transactions
FROM @LITECOIN_STAGE
FILE_FORMAT = (FORMAT_NAME = LITECOIN_TSV_FORMAT)
PATTERN = '.*transactions.*'
ON_ERROR = 'skip_file';

COPY INTO blocks
FROM @LITECOIN_STAGE
FILE_FORMAT = (FORMAT_NAME = LITECOIN_TSV_FORMAT)
PATTERN = '.*blocks.*'
ON_ERROR = 'skip_file';

COPY INTO inputs
FROM @LITECOIN_STAGE
FILE_FORMAT = (FORMAT_NAME = LITECOIN_TSV_FORMAT)
PATTERN = '.*inputs.*'
ON_ERROR = 'skip_file';

COPY INTO addresses
FROM @LITECOIN_STAGE
FILE_FORMAT = (FORMAT_NAME = LITECOIN_TSV_FORMAT)
PATTERN = '.*addresses.*'
ON_ERROR = 'skip_file';