CREATE OR REPLACE FILE FORMAT LITECOIN_TSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = '\t'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('', 'NULL')
COMMENT = 'Litecoin TSV file format with NULL handling';
