CREATE OR REPLACE TABLE outputs (
    BLOCK_ID INTEGER,
    TRANSACTION_HASH VARCHAR(255),
    INDEX INTEGER,
    TIME TIMESTAMP,
    VALUE INTEGER,
    VALUE_USD FLOAT,
    RECIPIENT VARCHAR(255),
    TYPE VARCHAR(255),
    SCRIPT_HEX VARCHAR(255),
    IS_FROM_COINBASE INTEGER,
    IS_SPENDABLE INTEGER
);